// FiveM resource generator: fxmanifest.lua + config.lua + client.lua + server.lua
import * as D from './door.js';

const n = (v, d = 4) => Number(v).toFixed(d);
const vec = (a) => `vector3(${n(a[0])}, ${n(a[1])}, ${n(a[2])})`;

export function buildResource({ door, an, pivot, resourceName, ytypFile, streamFiles, withScript = true, audioFile = null, soundLabel = null, anim = null, modelName = null }) {
  if (anim) return buildAnimResource({ door, an, resourceName, ytypFile, streamFiles, anim, modelName: modelName || door.name });
  const ms = D.motionSpec(door, an, pivot);
  const name = door.name;
  const dur = D.duration(door);
  const typeLabel = door.type === 'garage' ? `garage (${door.garage.kind})` : door.type;
  const native = door.engine === 'native';

  const manifest = `-- Generated by GTA Door Creator
fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name '${resourceName}'
description 'Door: ${name} (${typeLabel}, ${native ? 'native door system' : 'scripted'})'
version '1.0.0'

this_is_a_map 'yes'

files {
  'stream/${ytypFile}',${audioFile ? `\n  'audio/${audioFile}',` : ''}
}

data_file 'DLC_ITYP_REQUEST' 'stream/${ytypFile}'${audioFile ? `\n\n-- door sound (GTA: ${soundLabel || 'vanilla'})\ndata_file 'AUDIO_GAMEDATA' 'audio/${audioFile.replace(/\.dat151\.rel$/, '.dat')}'` : ''}

${withScript ? "shared_script 'config.lua'\nclient_script 'client.lua'\nserver_script 'server.lua'\n" : '-- no scripts: the GTA door system drives this door (archetype specialAttribute + Enable Door Physics)\n'}`;

  const config = `-- Generated by GTA Door Creator - edit freely
Config = {}

Config.Model = GetHashKey('${name}')   -- archetype in stream/${ytypFile}
Config.Engine = '${door.engine}'   -- 'native' = GTA door system (pushable physics door), 'scripted' = animated by this resource
Config.Type = '${door.type}'${door.type === 'garage' ? `       -- ${door.garage.kind}` : ''}

-- Motion in model space (the model origin is the pivot you set in the app)
Config.Motion = {
  kind   = '${ms.kind}',
  axis   = ${vec(ms.axis)},
  angle  = ${n(ms.angle, 2)},      -- degrees at fully open
  center = ${vec(ms.center)},      -- rotation centre
  offset = ${vec(ms.offset)},      -- translation at fully open
}
Config.Duration = ${n(dur, 2)}       -- seconds for a full open (${door.speed})

Config.Key = 38                     -- E
Config.InteractDistance = ${n(Math.max(1.6, Math.min(4, an.size[an.widthAxis] * 0.9 + 0.8)), 2)}
Config.StartLocked = false          -- native doors: start locked?
Config.AutoClose = 0                -- scripted doors: seconds before closing automatically (0 = never)
Config.HelpText = true

-- Optional: fixed instances (from your ymap/MLO). Leave empty to handle every placed copy of the model.
-- Config.Doors = { vector3(123.4, -456.7, 28.9) }
Config.Doors = {}
`;

  const client = `-- Generated by GTA Door Creator
local doors = {}          -- [id] = { ent, basePos, baseQuat, ratio, target, from, t0, dur, locked }
local state = {}          -- [id] = { open = bool, locked = bool }  (from the server)
local RES = GetCurrentResourceName()

local function round(v) return math.floor(v * 10 + 0.5) / 10 end
local function doorId(c) return ('%.1f_%.1f_%.1f'):format(round(c.x), round(c.y), round(c.z)) end

-- quaternion helpers (x, y, z, w)
local function qmul(a, b)
  return {
    a[4]*b[1] + a[1]*b[4] + a[2]*b[3] - a[3]*b[2],
    a[4]*b[2] - a[1]*b[3] + a[2]*b[4] + a[3]*b[1],
    a[4]*b[3] + a[1]*b[2] - a[2]*b[1] + a[3]*b[4],
    a[4]*b[4] - a[1]*b[1] - a[2]*b[2] - a[3]*b[3],
  }
end
local function qrot(q, v)
  local x, y, z, w = q[1], q[2], q[3], q[4]
  local ix =  w*v.x + y*v.z - z*v.y
  local iy =  w*v.y + z*v.x - x*v.z
  local iz =  w*v.z + x*v.y - y*v.x
  local iw = -x*v.x - y*v.y - z*v.z
  return vector3(ix*w + iw*-x + iy*-z - iz*-y, iy*w + iw*-y + iz*-x - ix*-z, iz*w + iw*-z + ix*-y - iy*-x)
end
local function qaxis(axis, deg)
  local h = math.rad(deg) * 0.5
  local l = #(axis)
  if l < 1e-6 then return {0.0, 0.0, 0.0, 1.0} end
  local s = math.sin(h) / l
  return { axis.x * s, axis.y * s, axis.z * s, math.cos(h) }
end
local function ease(t) if t < 0.5 then return 2*t*t end return 1 - ((-2*t + 2)^2) / 2 end

-- place the door at open ratio r (0 closed .. 1 open) relative to its map transform
local function applyRatio(d, r)
  local e = ease(r)
  local M = Config.Motion
  local ql = qaxis(M.axis, M.angle * e)
  local C = M.center
  local localShift = (C - qrot(ql, C)) + M.offset * e
  local pos = d.basePos + qrot(d.baseQuat, localShift)
  local q = qmul(d.baseQuat, ql)
  SetEntityCoordsNoOffset(d.ent, pos.x, pos.y, pos.z, false, false, false)
  SetEntityQuaternion(d.ent, q[1], q[2], q[3], q[4])
end

local function track(ent)
  local c = GetEntityCoords(ent)
  local id = doorId(c)
  local d = doors[id]
  if d and d.ent == ent then return id, d end
  if d and DoesEntityExist(d.ent) then return id, d end
  local qx, qy, qz, qw = GetEntityQuaternion(ent)
  d = { ent = ent, basePos = c, baseQuat = { qx, qy, qz, qw }, ratio = 0.0, target = 0.0 }
  doors[id] = d
  if Config.Engine == 'scripted' then
    FreezeEntityPosition(ent, true)
    local st = state[id]
    if st and st.open then d.ratio, d.target = 1.0, 1.0; applyRatio(d, 1.0) end
  else
    local hash = GetHashKey(RES .. ':' .. id)
    d.hash = hash
    if not IsDoorRegisteredWithSystem(hash) then
      AddDoorToSystem(hash, Config.Model, c.x, c.y, c.z, false, false, false)
    end
    local st = state[id]
    local locked = (st and st.locked) or (st == nil and Config.StartLocked)
    DoorSystemSetDoorState(hash, locked and 1 or 0, false, true)
  end
  return id, d
end

local function setTarget(id, open)
  local d = doors[id]
  if not d or not DoesEntityExist(d.ent) then return end
  d.from, d.target, d.t0 = d.ratio, open and 1.0 or 0.0, GetGameTimer()
  d.dur = math.max(50, Config.Duration * 1000 * math.abs(d.target - d.ratio))
end

RegisterNetEvent(RES .. ':set', function(id, st)
  state[id] = st
  local d = doors[id]
  if not d then return end
  if Config.Engine == 'scripted' then setTarget(id, st.open)
  elseif d.hash then DoorSystemSetDoorState(d.hash, st.locked and 1 or 0, false, true) end
end)

RegisterNetEvent(RES .. ':all', function(all) state = all or {} end)

local function help(msg)
  BeginTextCommandDisplayHelp('STRING')
  AddTextComponentSubstringPlayerName(msg)
  EndTextCommandDisplayHelp(0, false, false, -1)
end

CreateThread(function()
  TriggerServerEvent(RES .. ':request')
  while true do
    local sleep = 500
    local ped = PlayerPedId()
    local p = GetEntityCoords(ped)
    local ent = GetClosestObjectOfType(p.x, p.y, p.z, Config.InteractDistance + 2.0, Config.Model, false, false, false)
    if ent ~= 0 and DoesEntityExist(ent) then
      local id, d = track(ent)
      local allowed = #Config.Doors == 0
      for _, c in ipairs(Config.Doors) do if #(d.basePos - c) < 1.0 then allowed = true end end
      if allowed and #(p - d.basePos) < Config.InteractDistance + 0.5 then
        sleep = 0
        local st = state[id] or {}
        if Config.HelpText then
          if Config.Engine == 'scripted' then
            help(('~INPUT_CONTEXT~ %s door'):format(st.open and 'Close' or 'Open'))
          else
            local locked = st.locked; if locked == nil then locked = Config.StartLocked end
            help(('~INPUT_CONTEXT~ %s door'):format(locked and 'Unlock' or 'Lock'))
          end
        end
        if IsControlJustReleased(0, Config.Key) then
          TriggerServerEvent(RES .. ':toggle', id)
        end
      end
    end
    Wait(sleep)
  end
end)

-- animation loop (scripted doors only)
CreateThread(function()
  while true do
    local busy = false
    if Config.Engine == 'scripted' then
      local now = GetGameTimer()
      for id, d in pairs(doors) do
        if d.t0 then
          if not DoesEntityExist(d.ent) then doors[id] = nil
          else
            busy = true
            local k = math.min(1.0, (now - d.t0) / d.dur)
            d.ratio = d.from + (d.target - d.from) * k
            applyRatio(d, d.ratio)
            if k >= 1.0 then d.t0 = nil end
          end
        end
      end
    end
    Wait(busy and 0 or 250)
  end
end)

AddEventHandler('onResourceStop', function(res)
  if res ~= RES then return end
  for _, d in pairs(doors) do
    if DoesEntityExist(d.ent) and Config.Engine == 'scripted' then applyRatio(d, 0.0) end
  end
end)
`;

  const server = `-- Generated by GTA Door Creator
local RES = GetCurrentResourceName()
local state = {}   -- [id] = { open = bool, locked = bool }
local closeAt = {}

RegisterNetEvent(RES .. ':request', function()
  TriggerClientEvent(RES .. ':all', source, state)
end)

RegisterNetEvent(RES .. ':toggle', function(id)
  if type(id) ~= 'string' or #id > 64 then return end
  local st = state[id] or { open = false, locked = Config.StartLocked }
  if Config.Engine == 'scripted' then
    st.open = not st.open
    if st.open and Config.AutoClose > 0 then closeAt[id] = os.time() + Config.AutoClose end
  else
    st.locked = not st.locked
  end
  state[id] = st
  TriggerClientEvent(RES .. ':set', -1, id, st)
end)

CreateThread(function()
  while true do
    Wait(1000)
    local now = os.time()
    for id, t in pairs(closeAt) do
      if now >= t then
        closeAt[id] = nil
        if state[id] and state[id].open then
          state[id].open = false
          TriggerClientEvent(RES .. ':set', -1, id, state[id])
        end
      end
    end
  end
end)

-- exports for other resources: exports['${resourceName}']:SetDoor(id, open, locked)
exports('SetDoor', function(id, open, locked)
  local st = state[id] or {}
  if open ~= nil then st.open = open end
  if locked ~= nil then st.locked = locked end
  state[id] = st
  TriggerClientEvent(RES .. ':set', -1, id, st)
end)
`;

  const readme = `${resourceName}
${'='.repeat(resourceName.length)}
Generated by GTA Door Creator.

Model ............ ${name}
Door type ........ ${typeLabel}
In-game engine ... ${!withScript ? 'NATIVE, NO SCRIPT (the GTA door system drives the door by itself)' : native ? 'NATIVE (GTA door system: physics, pushable, lockable with E)' : 'SCRIPTED (opens/closes with E, synced for all players)'}
Archetype ........ specialAttribute ${D.specialAttribute(door)} (${D.SPECIAL_ATTR_NAMES[D.specialAttribute(door)]}), flags ${door.ytyp.flags}

INSTALL
1. Copy this folder into your server's resources.
2. Add  ensure ${resourceName}  to server.cfg.
3. Place the model "${name}" in your ymap / MLO (CodeWalker), or spawn it with CreateObject.

FILES
${streamFiles.map((f) => '  stream/' + f).join('\n')}
  fxmanifest.lua${withScript ? ', config.lua, client.lua, server.lua' : ''}

Collision is embedded inside the .ydr (it moves with the door).
${audioFile ? `Door sound: ${soundLabel} (audio/${audioFile}, GTA's own sounds, no script).\n` : ''}
The model origin is the pivot you set in GTA Door Creator, so the door
rotates/slides around it. Collision is embedded in the .ydr.
`;
  if (!withScript) return { 'fxmanifest.lua': manifest, 'README.txt': readme };
  return { 'fxmanifest.lua': manifest, 'config.lua': config, 'client.lua': client, 'server.lua': server, 'README.txt': readme };
}

// ------------------------------------------------------------------ ANIMATED .YCD resource
// The door is an animated fragment: the clips move the door bone, the expression (.yed) makes the
// collision follow it. Lua only plays the clips - it never moves the entity or touches its collision.
function buildAnimResource({ door, an, resourceName, ytypFile, streamFiles, anim, modelName }) {
  const dur = D.duration(door);
  const typeLabel = door.type === 'garage' ? `garage (${door.garage.kind})` : door.type;
  const manifest = `-- Generated by GTA Door Creator
fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name '${resourceName}'
description 'Door: ${modelName} (${typeLabel}, animated .ycd)'
version '1.0.0'

this_is_a_map 'yes'

files {
  'stream/${ytypFile}',
}

data_file 'DLC_ITYP_REQUEST' 'stream/${ytypFile}'

shared_script 'config.lua'
client_script 'client.lua'
server_script 'server.lua'
`;

  const config = `-- Generated by GTA Door Creator - edit freely
Config = {}

Config.Model = GetHashKey('${modelName}')   -- animated fragment (stream/${modelName}.yft)
Config.AnimDict = '${anim.dict}'            -- stream/${anim.dict}.ycd
Config.ClipOpen = '${anim.open}'
Config.ClipClose = '${anim.close}'
Config.Duration = ${n(dur, 2)}               -- seconds (baked in the clips)

Config.Key = 38                     -- E
Config.InteractDistance = ${n(Math.max(1.6, Math.min(4, an.size[an.widthAxis] * 0.9 + 0.8)), 2)}
Config.AutoClose = 0                -- seconds before closing automatically (0 = never)
Config.HelpText = true
Config.SyncDistance = 120.0         -- open doors are re-opened when they stream in within this distance

-- Optional: fixed instances (from your ymap/MLO). Leave empty to handle every placed copy of the model.
-- Config.Doors = { vector3(123.4, -456.7, 28.9) }
Config.Doors = {}
`;

  const client = `-- Generated by GTA Door Creator
-- Plays the door clips. Never move the entity, freeze it or change its collision:
-- the collision follows the animation by itself (fragment + expression).
local RES = GetCurrentResourceName()
local state = {}   -- [id] = { open = bool, x, y, z }  (from the server)

local function round(v) return math.floor(v * 10 + 0.5) / 10 end
local function doorId(c) return ('%.1f_%.1f_%.1f'):format(round(c.x), round(c.y), round(c.z)) end

local function loadDict()
  if HasAnimDictLoaded(Config.AnimDict) then return true end
  RequestAnimDict(Config.AnimDict)
  local timeout = GetGameTimer() + 5000
  while not HasAnimDictLoaded(Config.AnimDict) do
    if GetGameTimer() > timeout then return false end
    Wait(0)
  end
  return true
end

-- play the open / close clip. instant = jump to the end (door streamed in while already open)
local function play(ent, open, instant)
  if not DoesEntityExist(ent) or not loadDict() then return end
  local clip = open and Config.ClipOpen or Config.ClipClose
  local other = open and Config.ClipClose or Config.ClipOpen
  local phase = 0.0
  if instant then
    phase = 1.0
  elseif IsEntityPlayingAnim(ent, Config.AnimDict, other, 3) then
    -- reverse from where the door is now
    phase = 1.0 - math.min(1.0, math.max(0.0, GetEntityAnimCurrentTime(ent, Config.AnimDict, other)))
  end
  PlayEntityAnim(ent, clip, Config.AnimDict, 1000.0, false, true, false, phase, 0)
end

local function allowed(c)
  if #Config.Doors == 0 then return true end
  for _, p in ipairs(Config.Doors) do if #(c - p) < 1.0 then return true end end
  return false
end

local function findDoor(x, y, z)
  local ent = GetClosestObjectOfType(x, y, z, 0.6, Config.Model, false, false, false)
  if ent ~= 0 and DoesEntityExist(ent) then return ent end
  return nil
end

RegisterNetEvent(RES .. ':set', function(id, st)
  state[id] = st
  local ent = findDoor(st.x, st.y, st.z)
  if ent then play(ent, st.open, false) end
end)

RegisterNetEvent(RES .. ':all', function(all) state = all or {} end)

local function help(msg)
  BeginTextCommandDisplayHelp('STRING')
  AddTextComponentSubstringPlayerName(msg)
  EndTextCommandDisplayHelp(0, false, false, -1)
end

-- interaction (E)
CreateThread(function()
  TriggerServerEvent(RES .. ':request')
  while true do
    local sleep = 500
    local p = GetEntityCoords(PlayerPedId())
    local ent = GetClosestObjectOfType(p.x, p.y, p.z, Config.InteractDistance + 2.0, Config.Model, false, false, false)
    if ent ~= 0 and DoesEntityExist(ent) then
      local c = GetEntityCoords(ent)
      if allowed(c) and #(p - c) < Config.InteractDistance + 0.5 then
        sleep = 0
        local st = state[doorId(c)] or {}
        if Config.HelpText then help(('~INPUT_CONTEXT~ %s door'):format(st.open and 'Close' or 'Open')) end
        if IsControlJustReleased(0, Config.Key) then
          TriggerServerEvent(RES .. ':toggle', doorId(c), c.x, c.y, c.z)
        end
      end
    end
    Wait(sleep)
  end
end)

-- keep open doors open: an entity that streams in again starts closed, so ask the game what it is playing
CreateThread(function()
  while true do
    Wait(1000)
    local p = GetEntityCoords(PlayerPedId())
    for _, st in pairs(state) do
      if st.open and #(p - vector3(st.x, st.y, st.z)) < Config.SyncDistance then
        local ent = findDoor(st.x, st.y, st.z)
        if ent and not IsEntityPlayingAnim(ent, Config.AnimDict, Config.ClipOpen, 3) then play(ent, true, true) end
      end
    end
  end
end)
`;

  const server = `-- Generated by GTA Door Creator
local RES = GetCurrentResourceName()
local state = {}   -- [id] = { open = bool, x, y, z }
local closeAt = {}

RegisterNetEvent(RES .. ':request', function()
  TriggerClientEvent(RES .. ':all', source, state)
end)

RegisterNetEvent(RES .. ':toggle', function(id, x, y, z)
  if type(id) ~= 'string' or #id > 64 then return end
  if type(x) ~= 'number' or type(y) ~= 'number' or type(z) ~= 'number' then return end
  local st = state[id] or { open = false }
  st.x, st.y, st.z = x, y, z
  st.open = not st.open
  if st.open and Config.AutoClose > 0 then closeAt[id] = os.time() + Config.AutoClose else closeAt[id] = nil end
  state[id] = st
  TriggerClientEvent(RES .. ':set', -1, id, st)
end)

CreateThread(function()
  while true do
    Wait(1000)
    local now = os.time()
    for id, t in pairs(closeAt) do
      if now >= t then
        closeAt[id] = nil
        if state[id] and state[id].open then
          state[id].open = false
          TriggerClientEvent(RES .. ':set', -1, id, state[id])
        end
      end
    end
  end
end)

-- exports for other resources: exports['${resourceName}']:SetDoor(id, open)  (id = 'x_y_z' rounded to 0.1, see client.lua)
exports('SetDoor', function(id, open)
  local st = state[id]
  if not st then return false end
  st.open = open and true or false
  TriggerClientEvent(RES .. ':set', -1, id, st)
  return true
end)
`;

  const readme = `${resourceName}
${'='.repeat(resourceName.length)}
Generated by GTA Door Creator.

Model ............ ${modelName}  (ANIMATED .YCD - GTA fragment)
Door type ........ ${typeLabel}
Clips ............ ${anim.dict}.ycd : ${anim.open} / ${anim.close}  (${n(dur, 2)} s)

INSTALL
1. Copy this folder into your server's resources.
2. Add  ensure ${resourceName}  to server.cfg.
3. Place the model "${modelName}" in your ymap / MLO (CodeWalker).
   Inside an MLO, add it to the MLO's entities (and its room), not to a separate ymap.
4. In-game: press E near the door.

AFTER CHANGING THE FILES: disconnect and reconnect to the server.
FiveM caches streamed files - a resource restart is not enough.

FILES
${streamFiles.map((f) => '  stream/' + f).join('\n')}
  fxmanifest.lua, config.lua, client.lua, server.lua

HOW IT WORKS
- ${modelName}.yft   the door as a fragment: a root bone and a "door" bone (the model origin is your pivot)
- ${anim.dict}.ycd   two clips that move the door bone
- ${modelName}.yed   expression: makes the collision follow the door bone
- ${ytypFile}  ASSET_TYPE_FRAGMENT, flags 537526816 (Dynamic + Auto Start Anim + Ambient Scale + Static), clipDictionary,
                     expression extension "${modelName}"
- client.lua only calls PlayEntityAnim. Do not add SetEntityCollision / FreezeEntityPosition /
  door-system natives for this model: they break the animated collision.
`;
  return { 'fxmanifest.lua': manifest, 'config.lua': config, 'client.lua': client, 'server.lua': server, 'README.txt': readme };
}
