const { contextBridge, ipcRenderer, webUtils, clipboard } = require('electron');

const inv = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);

contextBridge.exposeInMainWorld('api', {
  coreStatus: inv('core:status'),
  load: inv('core:load'),
  exportFiles: inv('core:export'),
  buildSample: inv('core:buildSample'),
  buildAudio: inv('core:audio'),
  splitPreview: inv('core:splitPreview'),
  destructAnim: inv('core:destructAnim'),
  treeScan: inv('core:treeScan'),
  texFind: inv('core:texFind'),
  texExport: inv('core:texExport'),
  texDeep: inv('core:texDeep'),
  treeBuild: inv('core:treeBuild'),
  openYmapDialog: inv('dialog:openYmap'),
  detectGta: inv('app:detectGta'),
  isGta: inv('app:isGta'),
  openPropDialog: inv('dialog:openProp'),
  openYbnDialog: inv('dialog:openYbn'),
  openYtypDialog: inv('dialog:openYtyp'),
  chooseFolder: inv('dialog:chooseFolder'),
  saveProjectDialog: inv('dialog:saveProject'),
  openProjectDialog: inv('dialog:openProject'),
  message: inv('dialog:message'),
  readText: inv('fs:readText'),
  writeText: inv('fs:writeText'),
  readB64: inv('fs:readB64'),
  writeB64: inv('fs:writeB64'),
  exists: inv('fs:exists'),
  mkdir: inv('fs:mkdir'),
  move: inv('fs:move'),
  remove: inv('fs:remove'),
  tempDir: inv('fs:tempDir'),
  list: inv('fs:list'),
  openPath: inv('shell:open'),
  showItem: inv('shell:show'),
  loadPresets: inv('presets:load'),
  savePresets: inv('presets:save'),
  loadSettings: inv('settings:load'),
  saveSettings: inv('settings:save'),
  info: inv('app:info'),
  shortcut: inv('app:shortcut'),
  uninstallInfo: inv('app:uninstallInfo'),
  uninstall: inv('app:uninstall'),
  openAppFolder: inv('app:openFolder'),
  copyText: (t) => { clipboard.writeText(String(t)); return true; },
  setTitle: (t) => ipcRenderer.send('win:title', t),
  setDirty: (d) => ipcRenderer.send('win:dirty', d),
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return file.path || null; } },
  onMenu: (cb) => ipcRenderer.on('menu', (_e, cmd) => cb(cmd)),
  onOpenProject: (cb) => ipcRenderer.on('open-project', (_e, p) => cb(p)),
});
